# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: hdjdnvurjdisnwdnmf84746dgfug8696jh97kgjr73bdbdheefhfgiyjheiwht9

test:
  secret_key_base: did84hw2kdkdejdnbnxmzmzlskdufjr792nf844jf940rkr04jf03jdyreksosi

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
